"""Add document_type to dim_rule_mapplet

Revision ID: 27a6d3f0f595
Revises: 002
Create Date: 2026-05-04 09:36:43.006857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a6d3f0f595'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_profiling_task_asset'), table_name='dim_profiling_task')
    op.drop_index(op.f('idx_profiling_task_org'), table_name='dim_profiling_task')
    op.drop_index(op.f('idx_profiling_task_project'), table_name='dim_profiling_task')
    op.drop_table('dim_profiling_task')
    op.drop_index(op.f('idx_profiling_run_org'), table_name='dim_profiling_run')
    op.drop_index(op.f('idx_profiling_run_start'), table_name='dim_profiling_run')
    op.drop_index(op.f('idx_profiling_run_status'), table_name='dim_profiling_run')
    op.drop_index(op.f('idx_profiling_run_task'), table_name='dim_profiling_run')
    op.drop_table('dim_profiling_run')
    op.drop_index(op.f('idx_column_value_freq_org'), table_name='fact_column_value_frequency')
    op.drop_index(op.f('idx_column_value_freq_run_key'), table_name='fact_column_value_frequency')
    op.drop_index(op.f('idx_value_freq_rank'), table_name='fact_column_value_frequency')
    op.drop_index(op.f('idx_value_freq_run'), table_name='fact_column_value_frequency')
    op.drop_index(op.f('idx_value_freq_run_column'), table_name='fact_column_value_frequency')
    op.drop_index(op.f('idx_value_freq_task'), table_name='fact_column_value_frequency')
    op.drop_index(op.f('idx_value_freq_task_time'), table_name='fact_column_value_frequency')
    op.drop_table('fact_column_value_frequency')
    op.drop_index(op.f('idx_sync_jobs_active'), table_name='sync_jobs')
    op.drop_index(op.f('idx_sync_jobs_connection'), table_name='sync_jobs')
    op.drop_index(op.f('idx_sync_jobs_org'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index(op.f('idx_column_name'), table_name='dim_column')
    op.drop_index(op.f('idx_column_org'), table_name='dim_column')
    op.drop_table('dim_column')
    op.drop_index(op.f('idx_column_datatype_org'), table_name='fact_column_datatype')
    op.drop_index(op.f('idx_column_datatype_run_key'), table_name='fact_column_datatype')
    op.drop_index(op.f('idx_datatype_category'), table_name='fact_column_datatype')
    op.drop_index(op.f('idx_datatype_run'), table_name='fact_column_datatype')
    op.drop_index(op.f('idx_datatype_run_column'), table_name='fact_column_datatype')
    op.drop_index(op.f('idx_datatype_task'), table_name='fact_column_datatype')
    op.drop_index(op.f('idx_datatype_task_time'), table_name='fact_column_datatype')
    op.drop_table('fact_column_datatype')
    op.drop_index(op.f('idx_dq_asset_name'), table_name='dim_dq_asset')
    op.drop_index(op.f('idx_dq_asset_org'), table_name='dim_dq_asset')
    op.drop_index(op.f('idx_dq_asset_path'), table_name='dim_dq_asset')
    op.drop_table('dim_dq_asset')
    op.drop_index(op.f('idx_sync_job_runs_org'), table_name='sync_job_runs')
    op.drop_index(op.f('idx_sync_runs_job'), table_name='sync_job_runs')
    op.drop_index(op.f('idx_sync_runs_start'), table_name='sync_job_runs')
    op.drop_index(op.f('idx_sync_runs_status'), table_name='sync_job_runs')
    op.drop_table('sync_job_runs')
    op.drop_index(op.f('idx_column_pattern_org'), table_name='fact_column_pattern')
    op.drop_index(op.f('idx_column_pattern_run_key'), table_name='fact_column_pattern')
    op.drop_index(op.f('idx_pattern_run'), table_name='fact_column_pattern')
    op.drop_index(op.f('idx_pattern_run_column'), table_name='fact_column_pattern')
    op.drop_index(op.f('idx_pattern_task'), table_name='fact_column_pattern')
    op.drop_index(op.f('idx_pattern_task_time'), table_name='fact_column_pattern')
    op.drop_table('fact_column_pattern')
    op.drop_index(op.f('idx_time_date'), table_name='dim_time')
    op.drop_index(op.f('idx_time_org'), table_name='dim_time')
    op.drop_index(op.f('idx_time_year_month'), table_name='dim_time')
    op.drop_table('dim_time')
    op.drop_index(op.f('idx_profiling_result_org'), table_name='fact_profiling_result')
    op.drop_index(op.f('idx_result_asset'), table_name='fact_profiling_result')
    op.drop_index(op.f('idx_result_column'), table_name='fact_profiling_result')
    op.drop_index(op.f('idx_result_metric_type'), table_name='fact_profiling_result')
    op.drop_index(op.f('idx_result_run'), table_name='fact_profiling_result')
    op.drop_index(op.f('idx_result_task'), table_name='fact_profiling_result')
    op.drop_index(op.f('idx_result_time'), table_name='fact_profiling_result')
    op.drop_index(op.f('idx_result_timestamp'), table_name='fact_profiling_result')
    op.drop_table('fact_profiling_result')
    op.drop_index(op.f('idx_api_log_endpoint'), table_name='fact_api_log')
    op.drop_index(op.f('idx_api_log_org'), table_name='fact_api_log')
    op.drop_index(op.f('idx_api_log_run'), table_name='fact_api_log')
    op.drop_index(op.f('idx_api_log_status'), table_name='fact_api_log')
    op.drop_index(op.f('idx_api_log_task'), table_name='fact_api_log')
    op.drop_index(op.f('idx_api_log_timestamp'), table_name='fact_api_log')
    op.drop_table('fact_api_log')
    op.drop_index(op.f('idx_connection_org'), table_name='dim_connection')
    op.drop_table('dim_connection')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_connection',
    sa.Column('connection_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('connection_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('connection_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_index(op.f('idx_connection_org'), 'dim_connection', ['org_id'], unique=False)
    op.create_table('fact_api_log',
    sa.Column('log_id', sa.BIGINT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('http_method', sa.VARCHAR(length=10), nullable=True),
    sa.Column('status_code', sa.INTEGER(), nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), nullable=True),
    sa.Column('request_payload', sa.TEXT(), nullable=True),
    sa.Column('response_payload', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('profiling_task_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('profiling_run_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('idx_api_log_timestamp'), 'fact_api_log', ['timestamp'], unique=False)
    op.create_index(op.f('idx_api_log_task'), 'fact_api_log', ['profiling_task_id'], unique=False)
    op.create_index(op.f('idx_api_log_status'), 'fact_api_log', ['status_code'], unique=False)
    op.create_index(op.f('idx_api_log_run'), 'fact_api_log', ['profiling_run_id'], unique=False)
    op.create_index(op.f('idx_api_log_org'), 'fact_api_log', ['org_id'], unique=False)
    op.create_index(op.f('idx_api_log_endpoint'), 'fact_api_log', ['endpoint'], unique=False)
    op.create_table('fact_profiling_result',
    sa.Column('result_id', sa.BIGINT(), nullable=False),
    sa.Column('profiling_run_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('profiling_task_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('dq_asset_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('column_id', sa.INTEGER(), nullable=False),
    sa.Column('time_id', sa.INTEGER(), nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('metric_value', sa.FLOAT(), nullable=True),
    sa.Column('column_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('run_timestamp', sa.DATETIME(), nullable=False),
    sa.Column('column_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('column_id_external', sa.VARCHAR(length=255), nullable=True),
    sa.Column('documented_data_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('inferred_data_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('inferred_patterns', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['dim_column.column_id'], ),
    sa.ForeignKeyConstraint(['dq_asset_id'], ['dim_dq_asset.dq_asset_id'], ),
    sa.ForeignKeyConstraint(['profiling_run_id'], ['dim_profiling_run.profiling_run_id'], ),
    sa.ForeignKeyConstraint(['profiling_task_id'], ['dim_profiling_task.profiling_task_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['dim_time.time_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('idx_result_timestamp'), 'fact_profiling_result', ['run_timestamp'], unique=False)
    op.create_index(op.f('idx_result_time'), 'fact_profiling_result', ['time_id'], unique=False)
    op.create_index(op.f('idx_result_task'), 'fact_profiling_result', ['profiling_task_id'], unique=False)
    op.create_index(op.f('idx_result_run'), 'fact_profiling_result', ['profiling_run_id'], unique=False)
    op.create_index(op.f('idx_result_metric_type'), 'fact_profiling_result', ['metric_type'], unique=False)
    op.create_index(op.f('idx_result_column'), 'fact_profiling_result', ['column_id'], unique=False)
    op.create_index(op.f('idx_result_asset'), 'fact_profiling_result', ['dq_asset_id'], unique=False)
    op.create_index(op.f('idx_profiling_result_org'), 'fact_profiling_result', ['org_id'], unique=False)
    op.create_table('dim_time',
    sa.Column('time_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('quarter', sa.INTEGER(), nullable=True),
    sa.Column('month', sa.INTEGER(), nullable=True),
    sa.Column('week', sa.INTEGER(), nullable=True),
    sa.Column('day', sa.INTEGER(), nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), nullable=True),
    sa.Column('day_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('month_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_weekend', sa.INTEGER(), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('time_id'),
    sa.UniqueConstraint('date')
    )
    op.create_index(op.f('idx_time_year_month'), 'dim_time', ['year', 'month'], unique=False)
    op.create_index(op.f('idx_time_org'), 'dim_time', ['org_id'], unique=False)
    op.create_index(op.f('idx_time_date'), 'dim_time', ['date'], unique=False)
    op.create_table('fact_column_pattern',
    sa.Column('pattern_id', sa.BIGINT(), nullable=False),
    sa.Column('profiling_run_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('profiling_task_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('column_id_external', sa.VARCHAR(length=255), nullable=False),
    sa.Column('column_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('domain_value', sa.VARCHAR(length=500), nullable=True),
    sa.Column('pattern_label', sa.VARCHAR(length=500), nullable=True),
    sa.Column('inferred_datatype', sa.VARCHAR(length=500), nullable=True),
    sa.Column('satisfied_count', sa.BIGINT(), nullable=True),
    sa.Column('satisfied_count_percent', sa.FLOAT(), nullable=True),
    sa.Column('total_rows', sa.BIGINT(), nullable=True),
    sa.Column('run_timestamp', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('run_key', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['profiling_run_id'], ['dim_profiling_run.profiling_run_id'], ),
    sa.ForeignKeyConstraint(['profiling_task_id'], ['dim_profiling_task.profiling_task_id'], ),
    sa.PrimaryKeyConstraint('pattern_id')
    )
    op.create_index(op.f('idx_pattern_task_time'), 'fact_column_pattern', ['profiling_task_id', 'run_timestamp'], unique=False)
    op.create_index(op.f('idx_pattern_task'), 'fact_column_pattern', ['profiling_task_id'], unique=False)
    op.create_index(op.f('idx_pattern_run_column'), 'fact_column_pattern', ['profiling_run_id', 'column_id_external'], unique=False)
    op.create_index(op.f('idx_pattern_run'), 'fact_column_pattern', ['profiling_run_id'], unique=False)
    op.create_index(op.f('idx_column_pattern_run_key'), 'fact_column_pattern', ['run_key'], unique=False)
    op.create_index(op.f('idx_column_pattern_org'), 'fact_column_pattern', ['org_id'], unique=False)
    op.create_table('sync_job_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sync_job_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=True),
    sa.Column('projects_processed', sa.INTEGER(), nullable=True),
    sa.Column('tasks_processed', sa.INTEGER(), nullable=True),
    sa.Column('runs_processed', sa.INTEGER(), nullable=True),
    sa.Column('results_inserted', sa.INTEGER(), nullable=True),
    sa.Column('errors_count', sa.INTEGER(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_sync_runs_status'), 'sync_job_runs', ['status'], unique=False)
    op.create_index(op.f('idx_sync_runs_start'), 'sync_job_runs', ['start_time'], unique=False)
    op.create_index(op.f('idx_sync_runs_job'), 'sync_job_runs', ['sync_job_id'], unique=False)
    op.create_index(op.f('idx_sync_job_runs_org'), 'sync_job_runs', ['org_id'], unique=False)
    op.create_table('dim_dq_asset',
    sa.Column('dq_asset_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_display_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('folder_path', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('folder_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('folder_display_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('object_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_path', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('asset_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('connection_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('dq_asset_id')
    )
    op.create_index(op.f('idx_dq_asset_path'), 'dim_dq_asset', ['full_path'], unique=False)
    op.create_index(op.f('idx_dq_asset_org'), 'dim_dq_asset', ['org_id'], unique=False)
    op.create_index(op.f('idx_dq_asset_name'), 'dim_dq_asset', ['object_name'], unique=False)
    op.create_table('fact_column_datatype',
    sa.Column('datatype_id', sa.BIGINT(), nullable=False),
    sa.Column('profiling_run_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('profiling_task_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('column_id_external', sa.VARCHAR(length=255), nullable=False),
    sa.Column('column_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('datatype_category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('inferred_datatype', sa.VARCHAR(length=500), nullable=True),
    sa.Column('frequency', sa.BIGINT(), nullable=True),
    sa.Column('frequency_percent', sa.FLOAT(), nullable=True),
    sa.Column('total_rows', sa.BIGINT(), nullable=True),
    sa.Column('run_timestamp', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('run_key', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['profiling_run_id'], ['dim_profiling_run.profiling_run_id'], ),
    sa.ForeignKeyConstraint(['profiling_task_id'], ['dim_profiling_task.profiling_task_id'], ),
    sa.PrimaryKeyConstraint('datatype_id')
    )
    op.create_index(op.f('idx_datatype_task_time'), 'fact_column_datatype', ['profiling_task_id', 'run_timestamp'], unique=False)
    op.create_index(op.f('idx_datatype_task'), 'fact_column_datatype', ['profiling_task_id'], unique=False)
    op.create_index(op.f('idx_datatype_run_column'), 'fact_column_datatype', ['profiling_run_id', 'column_id_external'], unique=False)
    op.create_index(op.f('idx_datatype_run'), 'fact_column_datatype', ['profiling_run_id'], unique=False)
    op.create_index(op.f('idx_datatype_category'), 'fact_column_datatype', ['datatype_category', 'profiling_run_id'], unique=False)
    op.create_index(op.f('idx_column_datatype_run_key'), 'fact_column_datatype', ['run_key'], unique=False)
    op.create_index(op.f('idx_column_datatype_org'), 'fact_column_datatype', ['org_id'], unique=False)
    op.create_table('dim_column',
    sa.Column('column_id', sa.INTEGER(), nullable=False),
    sa.Column('column_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('data_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('column_id'),
    sa.UniqueConstraint('column_name')
    )
    op.create_index(op.f('idx_column_org'), 'dim_column', ['org_id'], unique=False)
    op.create_index(op.f('idx_column_name'), 'dim_column', ['column_name'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('connection_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('connection_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sync_mode', sa.VARCHAR(length=50), nullable=True),
    sa.Column('task_limit', sa.INTEGER(), nullable=True),
    sa.Column('schedule_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('schedule_cron', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_sync_jobs_org'), 'sync_jobs', ['org_id'], unique=False)
    op.create_index(op.f('idx_sync_jobs_connection'), 'sync_jobs', ['connection_id'], unique=False)
    op.create_index(op.f('idx_sync_jobs_active'), 'sync_jobs', ['is_active'], unique=False)
    op.create_table('fact_column_value_frequency',
    sa.Column('value_frequency_id', sa.BIGINT(), nullable=False),
    sa.Column('profiling_run_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('profiling_task_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('column_id_external', sa.VARCHAR(length=255), nullable=False),
    sa.Column('column_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('column_value', sa.TEXT(), nullable=True),
    sa.Column('frequency', sa.BIGINT(), nullable=True),
    sa.Column('percent', sa.FLOAT(), nullable=True),
    sa.Column('is_outlier', sa.INTEGER(), nullable=True),
    sa.Column('value_rank', sa.INTEGER(), nullable=True),
    sa.Column('run_timestamp', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('run_key', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['profiling_run_id'], ['dim_profiling_run.profiling_run_id'], ),
    sa.ForeignKeyConstraint(['profiling_task_id'], ['dim_profiling_task.profiling_task_id'], ),
    sa.PrimaryKeyConstraint('value_frequency_id')
    )
    op.create_index(op.f('idx_value_freq_task_time'), 'fact_column_value_frequency', ['profiling_task_id', 'run_timestamp'], unique=False)
    op.create_index(op.f('idx_value_freq_task'), 'fact_column_value_frequency', ['profiling_task_id'], unique=False)
    op.create_index(op.f('idx_value_freq_run_column'), 'fact_column_value_frequency', ['profiling_run_id', 'column_id_external'], unique=False)
    op.create_index(op.f('idx_value_freq_run'), 'fact_column_value_frequency', ['profiling_run_id'], unique=False)
    op.create_index(op.f('idx_value_freq_rank'), 'fact_column_value_frequency', ['profiling_run_id', 'value_rank'], unique=False)
    op.create_index(op.f('idx_column_value_freq_run_key'), 'fact_column_value_frequency', ['run_key'], unique=False)
    op.create_index(op.f('idx_column_value_freq_org'), 'fact_column_value_frequency', ['org_id'], unique=False)
    op.create_table('dim_profiling_run',
    sa.Column('profiling_run_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('profiling_task_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('run_key', sa.VARCHAR(length=50), nullable=True),
    sa.Column('run_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('run_start_time', sa.DATETIME(), nullable=True),
    sa.Column('run_end_time', sa.DATETIME(), nullable=True),
    sa.Column('run_duration_seconds', sa.INTEGER(), nullable=True),
    sa.Column('run_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('row_count', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['profiling_task_id'], ['dim_profiling_task.profiling_task_id'], ),
    sa.PrimaryKeyConstraint('profiling_run_id')
    )
    op.create_index(op.f('idx_profiling_run_task'), 'dim_profiling_run', ['profiling_task_id'], unique=False)
    op.create_index(op.f('idx_profiling_run_status'), 'dim_profiling_run', ['run_status'], unique=False)
    op.create_index(op.f('idx_profiling_run_start'), 'dim_profiling_run', ['run_start_time'], unique=False)
    op.create_index(op.f('idx_profiling_run_org'), 'dim_profiling_run', ['org_id'], unique=False)
    op.create_table('dim_profiling_task',
    sa.Column('profiling_task_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('dq_asset_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('profiling_name', sa.VARCHAR(length=500), nullable=True),
    sa.Column('profiling_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('frs_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('project_display_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('folder_path', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('folder_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('folder_display_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('full_path', sa.VARCHAR(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['dq_asset_id'], ['dim_dq_asset.dq_asset_id'], ),
    sa.PrimaryKeyConstraint('profiling_task_id')
    )
    op.create_index(op.f('idx_profiling_task_project'), 'dim_profiling_task', ['project_name'], unique=False)
    op.create_index(op.f('idx_profiling_task_org'), 'dim_profiling_task', ['org_id'], unique=False)
    op.create_index(op.f('idx_profiling_task_asset'), 'dim_profiling_task', ['dq_asset_id'], unique=False)
    # ### end Alembic commands ###
